name       : isl
version    : '0.24'
release    : 5
source     :
    - https://libisl.sourceforge.io/isl-0.24.tar.xz : 043105cc544f416b48736fff8caf077fb0663a717d06b1113f16e391ac99ebad
license    : MIT
component  : system.base
emul32     : yes
summary    : Integer Set Library
description: |
    The ISL library for GCC graphite loop optimisations
builddeps  :
    - gmp-32bit-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
