name       : isl
version    : '0.20'
release    : 2
source     :
    - http://isl.gforge.inria.fr/isl-0.20.tar.xz : a5596a9fb8a5b365cb612e4b9628735d6e67e9178fae134a816ae195017e77aa
license    : MIT
component  : system.base
emul32     : yes
summary    : Integer Set Library
description: |
    The ISL library for GCC graphite loop optimisations
builddeps  :
    - gmp-32bit-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
